# Generated by Django 5.2 on 2025-04-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
