# Generated by Django 5.2 on 2025-04-21 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0002_venda_quantidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(unique=True)),
                ('calculation_type', models.CharField(choices=[('percent', 'Percentual'), ('fixed', 'Fixo por unidade')], default='percent', max_length=10, verbose_name='Tipo')),
                ('percent', models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 5.00 para 5% (use apenas se tipo=percent)', max_digits=5, null=True, verbose_name='Percentual')),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 2.50 (use apenas se tipo=fixed)', max_digits=10, null=True, verbose_name='Valor fixo por unidade')),
            ],
            options={
                'verbose_name': 'Regra de Comissão',
                'verbose_name_plural': 'Regras de Comissão',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='CommissionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('earner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_commissions', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
                'ordering': ['-created_at'],
            },
        ),
    ]
