# Generated by Django 5.2 on 2025-04-29 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_referral_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='referral_parent',
        ),
        migrations.AddField(
            model_name='customuser',
            name='indicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que indicou'),
        ),
    ]
