# Generated by Django 5.2 on 2025-04-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_customuser_referral_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='indicado_por',
            new_name='referral_parent',
        ),
    ]
