# Generated by Django 5.2 on 2025-04-29 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_indicado_por_customuser_referral_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='referral_parent',
        ),
        migrations.AddField(
            model_name='customuser',
            name='indicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicados', to=settings.AUTH_USER_MODEL),
        ),
    ]
